### ISSUE TITLE
UI Test Cases

### ISSUE THREAD

**Issue by theresa-cy-ngo** [CMPUT301F15T09/Cloud9#5]
As of November 20, 2015 we have model tests for the following use cases, but no UI tests:

-AttachItemPhotograph
-ViewItemPhotograph
-DeleteItemPhotograph

Also, some of the UI tests are combined together (eg. testMyInventoryUI covers use cases 5, 6, and 7). Is that okay? Or does it also have to be at least 1 UI test case:1 use case ratio?

**Comment by ayunita** [comment]
Well, it would be better if we make it into 1 UI test case:1 use case, it is more readable and easy to trace. But it should be fine as long we put the comment on it. Looks like "Delete Item Photograph" has not been implemented. What we have right now is "Cancel Photo", I don't know if it has the same functionality as "Delete Photo".

**Comment by theresa-cy-ngo** [comment]
I think "Delete Item Photograph" is when we have an item photograph and we want to remove it from the item...? I'm not sure if that's what "Cancel Photo" does, though. I'll check the code when I get home, but for now... just from looking at the test cases, those are the ones that don't have UI tests.
