### ISSUE TITLE
Owner accepts Trade issue

### ISSUE THREAD

**Issue by ayunita** [CMPUT301F15T09/Cloud9#8]
Issue: when owner accepts the trade, if owner goes to "Trade Record", owner can see " <borrower> offered a trade for <thing>" in his current record.
How do we suppose to handle this? Is this ok? or the trade should be marked as "completed" or remove it from owner trade? Any thought?

**Comment by ayunita** [comment]
It is actually a bug
Issue: (Owner)
click on a trade -> accept -> click again on the same trade, you can see "accept" button still there, which means the first click might not change anything to trade object.

**Comment by ayunita** [comment]
Issue: (under Trade Record)
There is a bug or logical error in Trades or RecordPageFragment for ArrayAdapter

**Comment by theresa-cy-ngo** [comment]
For the first issue, if the owner accepts a trade, then they should still see it as a current trade that's been accepted and "offered to you (owner)". It doesn't go into "completed" until the owner sets the trade as complete themselves when the borrower and owner trade their items.

Working on the other issues now~

**Comment by ayunita** [comment]
Accepted problem is fixed now. However there is another problem with STATUS of trade.
How many status should we have? 5? 6?
